version: '2'
services:
    okrserver-app:
        image: okrserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://okrserver-mysql:3306/okrserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    okrserver-mysql:
        extends:
            file: mysql.yml
            service: okrserver-mysql
